kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: YnJgN7q7bOT1xBm/SA9HzgD6J1sY/Z1ZmaVV7VFmvSM=
      - identity: {}
