global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#reddare_test'

