version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net 
  ui:
    image: ${USERNAME}/ui:${UIVER}
    ports:
      - ${UIPORT}:${UIPORT}/tcp
    networks:
      - front_net 
  post:
    image: ${USERNAME}/post:${POSTVER}
    networks:
      - front_net
      - back_net 
  comment:
    image: ${USERNAME}/comment:${COMMENTVER}
    networks:
      - front_net
      - back_net 

volumes:
  post_db:

networks:
  front_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24 
  back_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24
